### ISSUE TITLE
Système de point et classement

### ISSUE THREAD

**Issue by Gynidark** [Grafikart/DiscordBot#1]
## Système de point

> **@Joe** : J'ai réglé mon problème grâce à **@Grafikart** mais je ne sais pas comment le remercier.

Grâce à cette fonctionnalité **@Joe** pourrait marquer cette commande ```!point @Grafikart ```
Maintenant **@Grafikart** à gagné 1 point .

## Système de classement
Pour rester dans la lancé du système de point, faut bien un système de classement pour voir ce qui ont réussi à satisfaire/aider.

Donc pour cela ```!top {number = 10}```
- **number** permettrais d'avoir un top plus grand entre 10 et 20. Par défaut il est a 10.

Une fois la commande tapé nous verrons: 
1.**Grafikart** à **12** points
2.**Gynidark** à **7** points
3 ...etc

Cette fonctionnalité serait top surtout pour voir les membres actif pour les nouveaux(ou non) mais aussi pour les personnes qui on reçu de l'aide puisse le remercier simplement et rapidement.

Voilà :smiley:

**Comment by Elhebert** [comment]
Je pense que l'idée est bonne, mais il y a trop de risque d'abus.

Des gens vont vouloir aider quelqu'un alors qu'il n'ont clairement ni les connaissances, ni les compétences, juste pour être dans le classement. 
D'autres vont vouloir se servir de ce classement pour se montrer plus important qu'un autre ou mieux faire valoir son avis, simplement parce qu'il est au dessus dans le classement, 
Et des gens vont se donner des points entre amis. Genre, tu m'en donne un, et je t'en donne un.

Je "**+1**" l'idée, mais je pense pas que son implémentation, au vu de la communauté soit une bonne chose.

**Comment by Gynidark** [comment]
Effectivement, tu n'as pas tord.

Reste à voir avec **@Grafikart** pour le choix, de l'ajouter ou non.
Dans tout les cas, il y aurait une grosse vérification à faire... et j'penses que ça serait le plus relou.

**Comment by Grafikart** [comment]
Le souci c'est que cela génère plus de problème que ça en règle selon moi. Il faut que les personnes aie envie de répondre pour que les réponses soient de qualité. En forçant les gens à répondre on va avoir des personnes qui répondent un peu à côté juste pour avoir des points.
